#' @title Inducer Information
#' 
#' @description
#' this functions returns the inducer and the configuration of a model
#' 
#' @param model A model object
#' @examples
#' cars.data <- Dataset(data = cars, target = "dist")
#' xgb <- InducerConstructer(configuration = list(nrounds = 10, verbose = 0), method = "XGBoost")
#' model.xgb <- fit(xgb, cars.data)
#' inducer(model.xgb)
#' @export
inducer <- function(model) {
  assertClass(model, "Model")
  model$inducer
}

#' @title Configuration Information
#' 
#' @description
#' this functions returns the configuration of a model 
#' 
#' @param model A model object
#' @examples
#' cars.data <- Dataset(data = cars, target = "dist")
#' xgb <- InducerConstructer(configuration = list(nrounds = 10, verbose = 0), method = "XGBoost")
#' model.xgb <- fit(xgb, cars.data)
#' configuration(model.xgb)
#' @export
configuration.Model <- function(model) {
  assertClass(model, "Model")
  model$inducer$configuration
}

#' @title Model Object
#' 
#' @description
#' this function gets the object generated by xgboost::xgboost
#' 
#' @param model A model object
#' @examples
#' cars.data <- Dataset(data = cars, target = "dist")
#' xgb <- InducerConstructer(configuration = list(nrounds = 10, verbose = 0), method = "XGBoost")
#' model.xgb <- fit(xgb, cars.data)
#' modelObject(model.xgb)
#' @export
modelObject <- function(model) {
  assertClass(model, "Model")
  return(model$model)
}

#' @title Model Info
#' 
#' @description
#' this function returns the training time in seconds of a model
#' 
#' @param model A model object
#' @examples
#' modelInfo(model.xgb)
#' @export
modelInfo <- function(model) {
  # Input Checks
  assertClass(model, "Model")
  
  start_time <- Sys.time()
  
  # Train the model
  # to do
  
  end_time <- Sys.time()
  training_time_sec <- as.numeric(difftime(end_time, start_time, units = "secs"))
  
  return(list(training.time.sec = training_time_sec))
}

#' @title Predictions for ModelXGBoost
#' 
#' @description
#' this function predicts the response variable using a trained ModelXGBoost object
#' 
#' @param model A model object
#' @param ... Additional arguments
#' @param newdata A data frame or Dataset with the new data
#' @param type A character string specifying the type of prediction: "response", "se" (standard error), or "prob" (probability). The default is "response".
#' 
#' @examples
#' cars.data <- Dataset(data = cars, target = "dist")
#' xgb <- InducerConstructer(configuration = list(nrounds = 10, verbose = 0), method = "XGBoost")
#' model.xgb <- fit(xgb, cars.data)
#' predict(model.xgb, newdata = data.frame(speed = 10))
#' prediction <- predict(model.xgb, newdata = cars.data[c(1, 2, 3, 4), ])
#' prediction
#' @export
predict.ModelXGBoost <- function(model, ..., newdata, type = "response") {
  # Input Checks
  assertClass(model, "ModelXGBoost")
  assertMultiClass(newdata, c("data.frame", "Dataset"))
  assertChoice(type, c("response", "se", "prob"))
  
  data <- if (is.data.frame(newdata)) newdata else as.data.frame(newdata)
  
  # select only the features
  data <- data[, modelObject(model)$feature_names, drop = FALSE]
  
  predictions <- predict(modelObject(model), newdata = as.matrix(data))
  
  if (is.data.frame(newdata)) {
    result <- predictions
  } else {
    result <-
      data.frame(prediction = predictions,
                 truth = as.data.frame(newdata, columns = "target"))
  }
  return(result)
}

#' @title Predictions for lm
#' 
#' @description
#' this function predicts the response variable using a trained lm model
#' 
#' @param model A model object
#' @param ... Additional arguments
#' @param newdata A data frame or Dataset with the new data
#' @param type A character string specifying the type of prediction: "response", "se" (standard error), or "prob" (probability). The default is "response".
#' 
#' @examples
#' model.lm <- lm(dist ~ speed, data = cars)
#' predict(model.lm, newdata = data.frame(speed = 10))
#' prediction <- predict(model.lm, newdata = cars.data[c(1, 2, 3, 4), ])
#' prediction
#' @export
predict.ModelLm <- function(model, ..., newdata, type = "response") {
  # Input Checks
  assertClass(model, "ModelLm")
  assertMultiClass(newdata, c("data.frame", "Dataset"))
  assertChoice(type, c("response", "se", "prob"))
  
  data <- if (is.data.frame(newdata)) newdata else as.data.frame(newdata)
  predictions <- predict(modelObject(model), newdata = data)
  
  if (is.data.frame(newdata)) {
    result <- predictions
  } else {
    result <- data.frame(prediction = predictions, truth = as.data.frame(newdata, columns = "target"))
  }
  return(result)
}


#' @title Predictions for Dummy
#' 
#' @description
#' this function predicts the majority class in a classification task or the average outcome in a regression task
#' 
#' @param model A model object
#' @param ... Additional arguments
#' @param newdata A data frame or Dataset with the new data
#' @param type A character string specifying the type of prediction: "response", "se" (standard error), or "prob" (probability). The default is "response".
#' 
#' @examples
#' model.dummy <- dummy(data = cars, target = "dist")
#' predict(model.dummy, newdata = data.frame(speed = 10))
#' prediction <- predict(model.dummy, newdata = cars.data[c(1, 2, 3, 4), ])
#' prediction
#' @export
predict.ModelDummy <- function(model, ..., newdata, type = "response") {
  # Input Checks
  # to do
  assertMultiClass(newdata, c("data.frame", "Dataset"))
  assertChoice(type, c("response", "se", "prob"))
  
  data <- ifelse(is.data.frame(newdata), newdata, newdata$data)
  
  if ("ModelRegression" %in% class(model)) {
    predictions <- mean(model$y)
  } else {
    predictions <- names(which.max(table(model$y)))
  }
  
  predict2(predictions)
}

#' @title Predictions for RandomForest
#' 
#' @description
#' this function predicts the response variable using a trained RandomForest model
#' 
#' @param model A model object
#' @param ... Additional arguments
#' @param newdata A data frame or Dataset with the new data
#' @param type A character string specifying the type of prediction: "response", "se" (standard error), or "prob" (probability). The default is "response".
#' 
#' @examples
#' model.rf <- rf(cars.data)
#' predict(model.rf, newdata = data.frame(speed = 10))
#' prediction <- predict(model.rf, newdata = cars.data[c(1, 2, 3, 4), ])
#' prediction
#' @export
predict.ModelRandomForest <- function(model, ..., newdata, type = "response") {
  # Input Checks
  # to do
  assertMultiClass(newdata, c("data.frame", "Dataset"))
  assertChoice(type, c("response", "se", "prob"))
  
  data <- if (is.data.frame(newdata)) newdata else as.data.frame(newdata)
  predictions <- predict(modelObject(model), newdata = data)
  
  if (is.data.frame(newdata)) {
    result <- predictions
  } else {
    result <- data.frame(prediction = predictions, truth = as.data.frame(newdata, columns = "target"))
  }
  return(result)
}

## Classes
# Model
# ModelRegression
# ModelClassification
# ModelXGBoost
# ModelLm
# ModelDummy
# ModelRandomForest
