library(checkmate)
source("R/Dataset.R")
source("R/Inducer.R")
source("R/InducerXgboost.R")

#' @title Inducer Information
#' 
#' @description
#' this functions returns the inducer and the configuration of a model
#' 
#' @param model A model object
#' @examples
#' cars.data <- Dataset(data = cars, target = "dist")
#' xgb <- InducerConstructer(configuration = list(nrounds = 10, verbose = 0), method = "XGBoost")
#' model.xgb <- fit(xgb, cars.data)
#' inducer(model.xgb)
#' @export
inducer <- function(model) {
  assertClass(model, "Model")
  model$inducer
}

#' @title Access configuration of a model
#' 
#' @description
#' this functions returns the configuration of a model 
#' 
#' @param x A model object
#' @examples
#' cars.data <- Dataset(data = cars, target = "dist")
#' xgb <- InducerConstructer(configuration = list(nrounds = 10, verbose = 0), method = "XGBoost")
#' model.xgb <- fit(xgb, cars.data)
#' configuration(model.xgb)
#' @export
configuration.Model <- function(x) {
  assertClass(x, "Model")
  x$inducer$configuration
}

#' @title Model Object
#' 
#' @description
#' this function gets the object generated by its inducer e.g. lm, xgboost::xgboost, randomForest::randomForest
#' 
#' @param model A model object
#' @examples
#' cars.data <- Dataset(data = cars, target = "dist")
#' xgb <- InducerConstructer(configuration = list(nrounds = 10, verbose = 0), method = "XGBoost")
#' model.xgb <- fit(xgb, cars.data)
#' modelObject(model.xgb)
#' @export
modelObject <- function(model) {
  assertClass(model, "Model")
  return(model$model)
}

#' @title Model Info
#' 
#' @description
#' this function returns the training time in seconds of a model
#' 
#' @param model A model object
#' @examples
#' cars.data <- Dataset(data = cars, target = "dist")
#' xgb <- InducerConstructer(configuration = list(nrounds = 10, verbose = 0), method = "XGBoost")
#' model.xgb <- fit(xgb, cars.data)
#' modelInfo(model.xgb)
#' @export
modelInfo <- function(model) {
  assertClass(model, "Model")
  
  training_time_sec <- model$training_time_sec
  return(list(training.time.sec = training_time_sec))
}

#' @title 'predict' method for `ModelXGBoost`
#' 
#' @description
#' this function predicts the response variable using a trained ModelXGBoost object
#' 
#' @param object A model object
#' @param ... Additional arguments
#' @param newdata A data frame or Dataset with the new data
#' @param type A character string specifying the type of prediction: "response", "se" (standard error), or "prob" (probability). The default is "response".
#' 
#' @examples
#' cars.data <- Dataset(data = cars, target = "dist")
#' xgb <- InducerConstructer(configuration = list(nrounds = 10, verbose = 0), method = "XGBoost")
#' model.xgb <- fit(xgb, cars.data)
#' predict(model.xgb, newdata = data.frame(speed = 10))
#' prediction <- predict(model.xgb, newdata = cars.data[c(1, 2, 3, 4), ])
#' prediction
#' @export
predict.ModelXGBoost <- function(object, ..., newdata, type = "response") {
  # Input Checks
  assertClass(object, "ModelXGBoost")
  assertMultiClass(newdata, c("data.frame", "Dataset"))
  assertChoice(type, c("response", "se", "prob"))
  
  if (type %in% c("se", "prob")) {
    stop("Standard errors and probability scores are not implemented yet.")
  }
  
  data <- if (is.data.frame(newdata)) newdata else as.data.frame(newdata)
  
  # select only the features
  data <- data[, modelObject(object)$feature_names, drop = FALSE]
  
  predictions <- predict(modelObject(object), newdata = as.matrix(data), ...)
  
  if (is.data.frame(newdata)) {
    result <- predictions
  } else {
    result <-
      data.frame(prediction = predictions,
                 truth = unname(as.data.frame(newdata, columns = "target")))
  }
  return(result)
}

#' @title 'predict' method for `ModelGlm`
#' 
#' @description
#' this function predicts the response variable using a trained glm model
#' 
#' @param object A model object
#' @param ... Additional arguments
#' @param newdata A data frame or Dataset with the new data
#' @param type A character string specifying the type of prediction: "response", "se" (standard error), or "prob" (probability). The default is "response".
#' 
#' @examples
#' cars.data <- Dataset(data = cars, target = "dist")
#' Glm <- InducerConstructer(configuration = list(family = "gaussian"), method = "Glm")
#' model.glm <- fit(Glm, cars.data)
#' predict(model.glm, newdata = data.frame(speed = 10))
#' @export
predict.ModelGlm <- function(object, ..., newdata, type = "response") {
  # Input Checks
  assertClass(object, "ModelGlm")
  assertMultiClass(newdata, c("data.frame", "Dataset"))
  assertChoice(type, c("response", "se", "prob"))
  
  if (type %in% c("se", "prob")) {
    stop("Standard errors and probability scores are not implemented yet.")
  }
  
  # if (type == "se" && "ModelClassification" %in% class(object)) {
  #   stop("Standard errors are only applicable for regression models.")
  # } else if (type == "prob" && "ModelRegression" %in% class(object)) {
  #   stop("Probability scores are only applicable for classification models.")
  # }
  
  data <- if (is.data.frame(newdata)) newdata else as.data.frame(newdata)
  
  predictions <- predict(modelObject(object), newdata = data, ...)
  
  
  if (is.data.frame(newdata)) {
    result <- predictions
  } else {
    result <-
      data.frame(prediction = predictions,
                 truth = as.data.frame(newdata, columns = "target"))
  }
  return(result)
}

#' @title 'predict' method for `ModelDummy`
#' 
#' @description
#' this function predicts the majority class in a classification task or the average outcome in a regression task
#' 
#' @param object A model object
#' @param ... Additional arguments
#' @param newdata A data frame or Dataset with the new data
#' @param type A character string specifying the type of prediction: "response", "se" (standard error), or "prob" (probability). The default is "response".
#' 
#' @export
predict.ModelDummy <- function(object, ..., newdata, type = "response") {
  # Input Checks
  assertMultiClass(newdata, c("data.frame", "Dataset"))
  assertChoice(type, c("response", "se", "prob"))
  
  if (type %in% c("se", "prob")) {
    stop("Standard errors and probability scores are not implemented yet.")
  }
  
  data <- if (is.data.frame(newdata)) newdata else as.data.frame(newdata)
  
  if ("ModelRegression" %in% class(object)) {
    predictions <- mean(object$y)
  } else {
    predictions <- names(which.max(table(object$y)))
  }
  
  if (is.data.frame(newdata)) {
    result <- predictions
  } else {
    result <-
      data.frame(prediction = predictions,
                 truth = as.data.frame(newdata, columns = "target"))
  }
  return(result)
}

#' @title 'predict' method for `ModelRandomForest`
#' 
#' @description
#' this function predicts the response variable using a trained RandomForest model
#' 
#' @param object A model object
#' @param ... Additional arguments
#' @param newdata A data frame or Dataset with the new data
#' @param type A character string specifying the type of prediction: "response", "se" (standard error), or "prob" (probability). The default is "response".
#' 
#' @export
predict.ModelRandomForest <- function(object, ..., newdata, type = "response") {
  # Input Checks
  assertMultiClass(newdata, c("data.frame", "Dataset"))
  assertChoice(type, c("response", "se", "prob"))
  
  if (type %in% c("se", "prob")) {
    stop("Standard errors and probability scores are not implemented yet.")
  }
  
  data <- if (is.data.frame(newdata)) newdata else as.data.frame(newdata)
  predictions <- predict(modelObject(object), newdata = data, ...)
  
  if (is.data.frame(newdata)) {
    result <- predictions
  } else {
    result <-
      data.frame(prediction = predictions,
                 truth = as.data.frame(newdata, columns = "target"))
  }
  return(result)
}